apiVersion: v1
kind: ConfigMap
metadata:
  # Имя ConfigMap - используется для ссылки
  name: {{ include "grafana.name" . }}-datasources
  # Метки для организации (опционально)
  labels:
    app: {{ include "grafana.name" . }}-datasources
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: {{ .Values.grafana.datasources.prometheus.name }}
        type: prometheus
        access: proxy
        url: {{ .Values.grafana.datasources.prometheus.url }}
        isDefault: true
        editable: true
        jsonData:
          timeInterval: "5s"