server:
  port: 8082

spring:
  application:
    name: account
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS_CONFIG:localhost:9092}
    topic:
      notification: ${NOTIFICATION_TOPIC:account-notification-topic}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=accounts}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:9090/realms/master}
  flyway:
    url: ${SPRING_FLYWAY_URL:jdbc:postgresql://localhost:5432/postgres}
    user: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    schemas: accounts
    default-schema: accounts
    enabled: true
    locations: classpath:db/migration
    table: schema_version
    sql-migration-prefix: V
    sql-migration-separator: __
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false