server:
  port: 8086
management:
  zipkin:
    endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,trace
spring:
  application:
    name: blocker
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS_CONFIG:localhost:9092}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:9090/realms/master}

kafka-log:
  topic:
    log: ${LOG_TOPIC:log-topic}