apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kibana.name" . }}
  # Дополнительные настройки для Ingress контроллера
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  # Список правил маршрутизации
  rules:
    - host: kibana.local
      http:
        paths:
          - path: /
            pathType: Prefix
            # Куда перенаправлять трафик
            backend:
              # Имя Service (должен существовать в том же namespace)
              service:
                name: {{ include "kibana.name" . }}
                # Порт Service (port в Service spec, не targetPort!)
                port:
                  number: {{ .Values.service.port }}