replicaCount: 1

image:
  tag: "latest"
  pullPolicy: Never

service:
  type: ClusterIP
  port: 80
  targetPort: 8085

config:
  database_url: "jdbc:postgresql://postgres-0.postgres:5432/postgres?currentSchema=notification"
  data_base_fly_way_url: "jdbc:postgresql://postgres-0.postgres:5432/postgres"
  database_username: "postgres"
  database_password: "postgres"
  account_notification_topic: "account-notification-topic"
  transfer_notification_topic: "transfer-notification-topic"
  cash_notification_topic: "cash-notification-topic"
  notification_group_id: "exchange"
  bootstrap: "kafka:9092"
  log_topic: "log-topic"
  zipkin_url: "http://zipkin/api/v2/spans"
