# Secret для чувствительных данных (пароли)
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "front.name" . }}
type: Opaque
stringData:
  account_client_secret: {{ .Values.config.account_client_secret }}
  cash_client_secret: {{ .Values.config.cash_client_secret }}
  transfer_client_secret: {{ .Values.config.transfer_client_secret }}