apiVersion: v1
kind: ConfigMap
metadata:
  # Имя ConfigMap - используется для ссылки
  name: {{ include "cash.name" . }}
  # Метки для организации (опционально)
  labels:
    app: {{ include "cash.name" . }}
data:
  #Quote нужен для экранирования
  SPRING_DATASOURCE_URL: {{ .Values.config.database_url | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.config.database_username }}
  SPRING_FLYWAY_URL: {{ .Values.config.data_base_fly_way_url | quote }}
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: {{ .Values.config.keycloak_url | quote }}
  SPRING_SECURITY_OAUTH2_PROVIDER_ISSUER_URI: {{ .Values.config.keycloak_url | quote }}
  ACCOUNT_GET_BALANCE_URL: {{ .Values.config.account_get_balance_url | quote }}
  ACCOUNT_PATCH_BALANCE_URL: {{ .Values.config.account_patch_balance_url | quote }}
  BLOCKER_URL: {{ .Values.config.blocker_url | quote }}
  BOOTSTRAP_SERVERS_CONFIG: {{ .Values.config.bootstrap | quote }}
  LOG_TOPIC: {{ .Values.config.log_topic | quote }}
  NOTIFICATION_TOPIC: {{ .Values.config.notification_topic | quote }}
  ZIPKIN_URL: {{ .Values.config.zipkin_url | quote }}