# Secret для чувствительных данных (пароли)
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cash.name" . }}
type: Opaque
stringData:
  password: {{ .Values.config.database_password }}
  blocker_client_secret: {{ .Values.config.blocker_client_secret }}
  account_client_secret: {{ .Values.config.account_client_secret }}