server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=exchange
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres
    schemas: exchange
    default-schema: exchange
    enabled: true
    locations: classpath:db/migration
    table: schema_version
    sql-migration-prefix: V
    sql-migration-separator: __
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/master