server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/master
        registration:
          account-client:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: account_client
            client-secret: cuqu6hPnGUhwcFlDijZLCYDZ8HuQJB4s
            scope: profile
            clientAuthenticationMethod: client_secret_post
          cash-client:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: cash_client
            client-secret: lIIF4SDSTlxvpZK4RfDwwgBDgiW3NNbU
            scope: profile
            clientAuthenticationMethod: client_secret_post
          transfer-client:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: transfer_client
            client-secret: izeEdZjAqR6gbTF2HtdUmQfXgQj0mRMf
            scope: profile
            clientAuthenticationMethod: client_secret_post

resilience4j:
  circuitbreaker:
    circuitBreakerAspectOrder: 1
    configs:
      default:
        slidingWindowSize: 20
        minimum-number-of-calls: 3
        permitted-number-of-calls-in-half-open-state: 5
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
        wait-duration-in-open-state: 10s
        max-wait-duration-in-half-open-state: 5s
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - java.lang.Throwable
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - java.net.ConnectException
          - java.net.SocketTimeoutException
    instances:
      accountService:
        base-config: default
        ignore-exceptions:
          - org.springframework.web.client.HttpClientErrorException$BadRequest
          - org.springframework.web.client.HttpClientErrorException$UnprocessableEntity
          - org.springframework.web.client.HttpClientErrorException$NotFound
          - org.springframework.web.client.HttpClientErrorException
      cashService:
        base-config: default
        ignore-exceptions:
          - org.springframework.web.client.HttpClientErrorException$BadRequest
          - org.springframework.web.client.HttpClientErrorException$UnprocessableEntity
          - org.springframework.web.client.HttpClientErrorException$NotFound
          - org.springframework.web.client.HttpClientErrorException
      transferService:
        base-config: default
        ignore-exceptions:
          - org.springframework.web.client.HttpClientErrorException$BadRequest
          - org.springframework.web.client.HttpClientErrorException$UnprocessableEntity
          - org.springframework.web.client.HttpClientErrorException$NotFound
          - org.springframework.web.client.HttpClientErrorException
  retry:
    retryAspectOrder: 2
    configs:
      default:
        max-attempts: 3
        wait-duration: 1s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        max-wait-duration: 5s
        retry-exceptions:
          - java.lang.Throwable
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - java.net.ConnectException
          - java.net.SocketTimeoutException
    instances:
      accountService:
        base-config: default
        ignore-exceptions:
          - org.springframework.web.client.HttpClientErrorException$BadRequest
          - org.springframework.web.client.HttpClientErrorException$UnprocessableEntity
          - org.springframework.web.client.HttpClientErrorException$NotFound
          - org.springframework.web.client.HttpClientErrorException
      cashService:
        base-config: default
        ignore-exceptions:
          - org.springframework.web.client.HttpClientErrorException$BadRequest
          - org.springframework.web.client.HttpClientErrorException$UnprocessableEntity
          - org.springframework.web.client.HttpClientErrorException$NotFound
          - org.springframework.web.client.HttpClientErrorException
      transferService:
        base-config: default
        ignore-exceptions:
          - org.springframework.web.client.HttpClientErrorException$BadRequest
          - org.springframework.web.client.HttpClientErrorException$UnprocessableEntity
          - org.springframework.web.client.HttpClientErrorException$NotFound
          - org.springframework.web.client.HttpClientErrorException
urls:
  account:
    get:
      account: http://account-service/account?login={login}
      full: http://account-service/account/full?login={login}
    create: http://account-service/account
    balance: http://account-service/account/balance
    patch:
      password: http://account-service/account/password
      info: http://account-service/account/info
  cash: http://cash-service/cash
  transfer:
    patch: http://transfer-service/transfer/transfer
    get: http://transfer-service/transfer/exchange