server:
  port: 8085

spring:
  application:
    name: notification
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=notification}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS_CONFIG:localhost:9092}
    topic:
      account: ${ACCOUNT_NOTIFICATION_TOPIC:account-notification-topic}
      transfer: ${TRANSFER_NOTIFICATION_TOPIC:transfer-notification-topic}
      cash: ${CASH_NOTIFICATION_TOPIC:cash-notification-topic}
    consumer:
      group-id: ${NOTIFICATION_GROUP_ID:notification}

  flyway:
    url: ${SPRING_FLYWAY_URL:jdbc:postgresql://localhost:5432/postgres}
    user: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    schemas: notification
    default-schema: notification
    enabled: true
    locations: classpath:db/migration
    table: schema_version
    sql-migration-prefix: V
    sql-migration-separator: __
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false