server:
  port: 8085

spring:
  application:
    name: notification
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=notification}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  flyway:
    url: ${SPRING_FLYWAY_URL:jdbc:postgresql://localhost:5432/postgres}
    user: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    schemas: notification
    default-schema: notification
    enabled: true
    locations: classpath:db/migration
    table: schema_version
    sql-migration-prefix: V
    sql-migration-separator: __
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:9090/realms/master}