global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9091" ]

  - job_name: "front"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "host.docker.internal:8081" ]
        labels:
          application: "front"

  - job_name: "account"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "host.docker.internal:8082" ]
        labels:
          application: "account"

  - job_name: "cash"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "host.docker.internal:8083" ]
        labels:
          application: "cash"

  - job_name: "transfer"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "host.docker.internal:8084" ]
        labels:
          application: "transfer"

  - job_name: "notification"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "host.docker.internal:8085" ]
        labels:
          application: "notification"

  - job_name: "blocker"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "host.docker.internal:8086" ]
        labels:
          application: "blocker"

  - job_name: "exchange"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "host.docker.internal:8087" ]
        labels:
          application: "exchange"

  - job_name: "generator"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "host.docker.internal:8088" ]
        labels:
          application: "generator"