server:
  port: 8088

spring:
  application:
    name: generator
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS_CONFIG:localhost:9092}
    topic:
      exchange: ${EXCHANGE_TOPIC:exchange-dto-list-topic}