spring:
  application:
    name: cash-service
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 3000
        multiplier: 1.3
        max-interval: 10000
  config:
    import: configserver:http://localhost:8080