server:
  port: 8083

spring:
  application:
    name: cash
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=cash}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS_CONFIG:localhost:9092}
    topic:
      notification: ${NOTIFICATION_TOPIC:cash-notification-topic}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:9090/realms/master}
      client:
        provider:
          keycloak:
            issuer-uri: ${SPRING_SECURITY_OAUTH2_PROVIDER_ISSUER_URI:http://localhost:9090/realms/master}
        registration:
          blocker-client:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: blocker_client
            client-secret: ${BLOCKER_CLIENT_SECRET:c81Y8FXddFGEQOchrQpmEzUyExFWybPM}
            scope: profile
            clientAuthenticationMethod: client_secret_post
          account-client:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: account_client
            client-secret: ${ACCOUNT_CLIENT_SECRET:cuqu6hPnGUhwcFlDijZLCYDZ8HuQJB4s}
            scope: profile
            clientAuthenticationMethod: client_secret_post

  flyway:
    url: ${SPRING_FLYWAY_URL:jdbc:postgresql://localhost:5432/postgres}
    user: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    schemas: cash
    default-schema: cash
    enabled: true
    locations: classpath:db/migration
    table: schema_version
    sql-migration-prefix: V
    sql-migration-separator: __
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false

resilience4j:
  circuitbreaker:
    circuitBreakerAspectOrder: 1
    configs:
      default:
        slidingWindowSize: 20
        minimum-number-of-calls: 3
        permitted-number-of-calls-in-half-open-state: 5
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
        wait-duration-in-open-state: 10s
        max-wait-duration-in-half-open-state: 5s
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - java.lang.Throwable
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.client.HttpClientErrorException
          - java.io.IOException
          - java.net.ConnectException
          - java.net.SocketTimeoutException
    instances:
      cashService:
        base-config: default
      blockerService:
        base-config: default

  retry:
    retryAspectOrder: 2
    configs:
      default:
        max-attempts: 3
        wait-duration: 1s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        max-wait-duration: 5s
        retry-exceptions:
          - java.lang.Throwable
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - java.net.ConnectException
          - java.net.SocketTimeoutException
    instances:
      cashService:
        base-config: default
        ignore-exceptions:
          - org.springframework.web.client.HttpClientErrorException$BadRequest
          - org.springframework.web.client.HttpClientErrorException$UnprocessableEntity
          - org.springframework.web.client.HttpClientErrorException$NotFound
          - org.springframework.web.client.HttpClientErrorException

urls:
  account:
    get:
      balance: ${ACCOUNT_GET_BALANCE_URL:http://localhost:8082/account/balance?login={login}&currency={currency}}
    patch:
      balance: ${ACCOUNT_PATCH_BALANCE_URL:http://localhost:8082/account/balance}
  blocker: ${BLOCKER_URL:http://localhost:8086/blocker/block}