apiVersion: apps/v1
kind: Deployment
# Метаданные объекта
metadata:
  # Имя Deployment. Уникальное в namespace, используется в командах kubectl
  name: {{ include "elastic.name" . }}
  # Метки для организации и выборки объектов
  labels:
    # Стандартная метка для идентификации приложения
    app: {{ include "elastic.name" . }}
# Спецификация - описывает желаемое состояние
spec:
  # Количество реплик (копий) приложения
  replicas: {{ .Values.replicaCount }}
  # Селектор - определяет какие поды управляются этим Deployment
  selector:
    # Ищет поды с метками, которые соответствуют этим
    matchLabels:
      # Будет управлять всными подами с этой меткой
      app: {{ include "elastic.name" . }}
  # Шаблон для создания новых подов
  template:
    # Метаданные создаваемых подов
    metadata:
      # Метки, которые будут присвоены создаваемым подам
      labels:
        # ЭТА МЕТКА ДОЛЖНА СОВПАДАТЬ С SELECTOR!
        app: {{ include "elastic.name" . }}
    # Спецификация контейнеров внутри пода
    spec:
      # Список контейнеров в поде (можно несколько)
      containers:
        # Имя контейнера внутри пода (для логирования, мониторинга)
        - name: {{ include "elastic.name" . }}
          # Docker образ для контейнера
          image: {{ .Values.image.full }}
          # Порт из конфига: server.port
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: discovery.type
              value: "single-node"
            - name: xpack.security.enabled
              value: {{ .Values.security.enabled | quote }}
            - name: xpack.security.enrollment.enabled
              value: {{ .Values.security.enrollment | quote }}
      volumes:
        # Задаётся имя волума для Pod
        - name: { { include "elastic.name" . } }
          persistentVolumeClaim:
            # Ссылается на имя PVC(Как флешка)
            claimName: { { include "elastic.name" . } }