apiVersion: v1
kind: ConfigMap
metadata:
  # Имя ConfigMap - используется для ссылки
  name: {{ include "prometheus.name" . }}
  # Метки для организации (опционально)
  labels:
    app: {{ include "prometheus.name" . }}
data:
  prometheus.yml: |
    {{ .Files.Get "prometheus.yml" | nindent 4 }}
