apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: {{ .Release.Name }}

data:
  server.properties: |
    process.roles={{ .Values.kafka.kraft.processRoles }}
    node.id={{ .Values.kafka.kraft.nodeId }}
    controller.quorum.voters={{ .Values.kafka.kraft.nodeId }}@localhost:9093

    log.dirs={{ .Values.kafka.persistence.mountPath }}
    num.partitions={{ .Values.kafka.config.numPartitions }}
    min.insync.replicas={{ .Values.kafka.config.minInsyncReplicas }}
    log.retention.hours={{ .Values.kafka.config.logRetentionHours }}
    transaction.state.log.min.isr={{ .Values.kafka.config.transactionStateLogMinIsr }}
    auto.create.topics.enable={{ .Values.kafka.config.autoCreateTopicsEnable }}
    default.replication.factor={{ .Values.kafka.config.defaultReplicationFactor }}
    offsets.topic.replication.factor={{ .Values.kafka.config.offsetsTopicReplicationFactor }}
    transaction.state.log.replication.factor={{ .Values.kafka.config.transactionStateLogReplicationFactor }}

    listeners=PLAINTEXT://:9092,CONTROLLER://:9093
    advertised.listeners=PLAINTEXT://kafka:9092
    listener.security.protocol.map=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
    controller.listener.names=CONTROLLER
    inter.broker.listener.name=PLAINTEXT

    kafka.kraft.cluster.id={{ .Values.kafka.kraft.clusterId }}