apiVersion: v1
kind: ConfigMap
metadata:
  # Имя ConfigMap - используется для ссылки
  name: {{ include "generator.name" . }}
  # Метки для организации (опционально)
  labels:
    app: {{ include "generator.name" . }}
data:
  #Quote нужен для экранирования
  BOOTSTRAP_SERVERS_CONFIG: {{ .Values.config.bootstrap | quote }}
  LOG_TOPIC: {{ .Values.config.log_topic | quote }}
  EXCHANGE_TOPIC: {{ .Values.config.exchange_topic | quote }}
  ZIPKIN_URL: {{ .Values.config.zipkin_url | quote }}