replicaCount: 1

image:
  tag: "latest"
  pullPolicy: Never

service:
  type: ClusterIP
  port: 80
  targetPort: 8088

config:
  #Лишний /keycloak из-за настройки внутри keycloak
  keycloak_url: "http://keycloak/keycloak/realms/master"
  exchange_url: "http://exchange/exchange/exchange"
  client_secret: "d2BXJ8UKxrdbF8TybLsZp0vsIGXCwt8Y"