replicaCount: 1

image:
  tag: "latest"
  pullPolicy: Never

service:
  type: ClusterIP
  port: 80
  targetPort: 8087

config:
  database_url: "jdbc:postgresql://postgres-0.postgres:5432/postgres?currentSchema=exchange"
  data_base_fly_way_url: "jdbc:postgresql://postgres-0.postgres:5432/postgres"
  database_username: "postgres"
  database_password: "postgres"
  keycloak_url: "http://keycloak/realms/master"
  exchange_topic: "exchange-dto-list-topic"
  exchange_group_id: "exchange"
  bootstrap: "kafka:9092"
  log_topic: "log-topic"
  zipkin_url: "http://zipkin/api/v2/spans"
