# Secret для чувствительных данных (пароли)
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notification.name" . }}
type: Opaque
stringData:
  password: {{ .Values.config.database_password }}