server:
  port: 8087
management:
  zipkin:
    endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,trace
spring:
  application:
    name: exchange
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=exchange}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS_CONFIG:localhost:9092}
    topic:
      exchange: ${EXCHANGE_TOPIC:exchange-dto-list-topic}
    consumer:
      group-id: ${EXCHANGE_GROUP_ID:exchange}
  flyway:
    url: ${SPRING_FLYWAY_URL:jdbc:postgresql://localhost:5432/postgres}
    user: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    schemas: exchange
    default-schema: exchange
    enabled: true
    locations: classpath:db/migration
    table: schema_version
    sql-migration-prefix: V
    sql-migration-separator: __
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:9090/realms/master}